import { PokemonType } from "./types/pokemonTypes";

export const POKEMONS_PER_PAGE = 9;
export const MAX_POKEMON = 150;

export const pokemonTypes: PokemonType[] = [
  { name: "bug", color: "#7bcf00", borderColor: "#67a700" },
  { name: "dark", color: "#5a566a", borderColor: "462e6a" },
  {
    name: "dragon",
    color: "#0076ff",
    borderColor: "#004eff",
  },
  {
    name: "electric",
    color: "#ffde00",
    borderColor: "#ebb600",
  },
  {
    name: "fairy",
    color: "#ff76ff",
    borderColor: "#eb4eff",
  },
  {
    name: "fighting",
    color: "#ff215b",
    borderColor: "#cd0056",
  },
  {
    name: "fire",
    color: "#ff9900",
    borderColor: "#e17100",
  },
  {
    name: "flying",
    color: "#89bdff",
    borderColor: "#cd4900",
  },
  {
    name: "ghost",
    color: "#4e6aff",
    borderColor: "#3a42ff",
  },
  {
    name: "grass",
    color: "#1cd80e",
    borderColor: "#08b00e",
  },
  {
    name: "ground",
    color: "#ff6b0d",
    borderColor: "#eb6b0d",
  },
  {
    name: "ice",
    color: "#2ee4c6",
    borderColor: "#1abcc6",
  },
  {
    name: "normal",
    color: "#9fa39d",
    borderColor: "#8b7b9d",
  },
  {
    name: "poison",
    color: "#f149ff",
    borderColor: "#dd21ff",
  },
  {
    name: "psychic",
    color: "#eb4464",
    borderColor: "#c4945a",
  },
  { name: "rock", color: "#d8bc5a", borderColor: "#c4945a" },
  {
    name: "steel",
    color: "#23a1bd",
    borderColor: "#0f79bd",
  },
  {
    name: "water",
    color: "#14a8ff",
    borderColor: "#0080ff",
  },
];

// export const pokemonTypesAgainst: PokemonTypesAgainstType[] = [
// 	{
// 		type: 'normal',
// 		strongAgainst: [''],
// 		weakAgainst: ['rock', 'ghost', 'steel'],
// 		resistantTo: ['ghost'],
// 		vulnerableTo: ['fighting'],
// 	},
// 	{
// 		type: 'fighting',
// 		strongAgainst: ['normal', 'rock', 'steel', 'ice', 'dark'],
// 		weakAgainst: ['flying', 'poison', 'psychic', 'bug', 'ghost', 'fairy'],
// 		resistantTo: ['rock', 'bug', 'dark'],
// 		vulnerableTo: ['flying', 'psychic', 'fairy'],
// 	},
// 	{
// 		type: 'flying',
// 		strongAgainst: ['fighting', 'bug', 'grass'],
// 		weakAgainst: ['rock', 'steel', 'electric'],
// 		resistantTo: ['fighting', 'ground', 'bug', 'grass'],
// 		vulnerableTo: ['rock', 'electric', 'ice'],
// 	},
// 	{
// 		type: 'poison',
// 		strongAgainst: ['grass', 'fairy'],
// 		weakAgainst: ['poison', 'ground', 'rock', 'ghost', 'steel'],
// 		resistantTo: ['fighting', 'poison', 'grass', 'fairy'],
// 		vulnerableTo: ['ground', 'psychic'],
// 	},
// 	{
// 		type: 'ground',
// 		strongAgainst: ['poison', 'rock', 'steel', 'fire', 'electric'],
// 		weakAgainst: ['flying', 'bug', 'grass'],
// 		resistantTo: ['poison', 'rock', 'electric'],
// 		vulnerableTo: ['water', 'grass', 'ice'],
// 	},
// 	{
// 		type: 'rock',
// 		strongAgainst: ['flying', 'bug', 'fire', 'ice'],
// 		weakAgainst: ['fighting', 'ground', 'steel'],
// 		resistantTo: ['normal', 'flying', 'poison', 'fire'],
// 		vulnerableTo: ['fighting', 'ground', 'steel', 'water', 'grass'],
// 	},
// 	{
// 		type: 'bug',
// 		strongAgainst: ['grass', 'psychic', 'dark'],
// 		weakAgainst: [
// 			'fighting',
// 			'flying',
// 			'poison',
// 			'ghost',
// 			'steel',
// 			'fire',
// 			'fairy',
// 		],
// 		resistantTo: ['fighting', 'ground', 'grass'],
// 		vulnerableTo: ['flying', 'rock', 'fire'],
// 	},
// 	{
// 		type: 'ghost',
// 		strongAgainst: ['ghost', 'psychic'],
// 		weakAgainst: ['normal', 'dark'],
// 		resistantTo: ['normal', 'fighting', 'poison', 'bug'],
// 		vulnerableTo: ['ghost', 'dark'],
// 	},
// 	{
// 		type: 'steel',
// 		strongAgainst: ['rock', 'ice', 'fairy'],
// 		weakAgainst: ['steel', 'fire', 'water', 'electric'],
// 		resistantTo: [
// 			'normal',
// 			'flying',
// 			'poison',
// 			'rock',
// 			'bug',
// 			'steel',
// 			'grass',
// 			'psychic',
// 			'ice',
// 			'dragon',
// 			'fairy',
// 		],
// 		vulnerableTo: ['fighting', 'ground', 'fire'],
// 	},
// 	{
// 		type: 'fire',
// 		strongAgainst: ['bug', 'steel', 'grass', 'ice'],
// 		weakAgainst: ['rock', 'fire', 'water', 'dragon'],
// 		resistantTo: ['bug', 'steel', 'fire', 'grass', 'ice'],
// 		vulnerableTo: ['ground', 'rock', 'water'],
// 	},
// 	{
// 		type: 'water',
// 		strongAgainst: ['ground', 'rock', 'fire'],
// 		weakAgainst: ['water', 'grass', 'dragon'],
// 		resistantTo: ['steel', 'fire', 'water', 'ice'],
// 		vulnerableTo: ['grass', 'electric'],
// 	},
// 	{
// 		type: 'grass',
// 		strongAgainst: ['ground', 'rock', 'water'],
// 		weakAgainst: [
// 			'flying',
// 			'poison',
// 			'bug',
// 			'steel',
// 			'fire',
// 			'grass',
// 			'dragon',
// 		],
// 		resistantTo: ['ground', 'water', 'grass', 'electric'],
// 		vulnerableTo: ['flying', 'poison', 'bug', 'fire', 'ice'],
// 	},
// 	{
// 		type: 'electric',
// 		strongAgainst: ['flying', 'water'],
// 		weakAgainst: ['ground', 'grass', 'electric', 'dragon'],
// 		resistantTo: ['flying', 'steel', 'electric'],
// 		vulnerableTo: ['ground'],
// 	},
// 	{
// 		type: 'psychic',
// 		strongAgainst: ['fighting', 'poison'],
// 		weakAgainst: ['steel', 'psychic', 'dark'],
// 		resistantTo: ['fighting', 'psychic'],
// 		vulnerableTo: ['bug', 'ghost', 'dark'],
// 	},
// 	{
// 		type: 'ice',
// 		strongAgainst: ['flying', 'ground', 'grass', 'dragon'],
// 		weakAgainst: ['steel', 'fire', 'water', 'ice'],
// 		resistantTo: ['ice'],
// 		vulnerableTo: ['fighting', 'rock', 'steel', 'fire'],
// 	},
// 	{
// 		type: 'dragon',
// 		strongAgainst: ['dragon'],
// 		weakAgainst: ['steel', 'fairy'],
// 		resistantTo: ['fire', 'water', 'grass', 'electric'],
// 		vulnerableTo: ['ice', 'dragon', 'fairy'],
// 	},
// 	{
// 		type: 'fairy',
// 		strongAgainst: ['fighting', 'dragon', 'dark'],
// 		weakAgainst: ['poison', 'steel', 'fire'],
// 		resistantTo: ['fighting', 'bug', 'dragon', 'dark'],
// 		vulnerableTo: ['poison', 'steel'],
// 	},
// 	{
// 		type: 'dark',
// 		strongAgainst: ['ghost', 'psychic'],
// 		weakAgainst: ['fighting', 'dark', 'fairy'],
// 		resistantTo: ['ghost', 'psychic', 'dark'],
// 		vulnerableTo: ['fighting', 'bug', 'fairy'],
// 	},
// ];
